# Generated by Django 2.2.4 on 2020-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('1', 'Київстар'), ('2', 'Лайфсел'), ('3', 'Тревел-сім')], help_text='Оберіть оператора', max_length=1, verbose_name='Оператор')),
                ('number', models.IntegerField(help_text='Введіть номер', max_length=12, verbose_name='Номер')),
                ('account_number', models.IntegerField(help_text='Введіть номер рахунку', max_length=12, verbose_name='Рахунок')),
                ('date_receive', models.DateField(help_text='Оберіть дату', verbose_name='Дата отримання')),
                ('rate', models.FloatField(help_text='Введіть суму', max_length=5, verbose_name='Тариф грн/міс')),
                ('packet_volume', models.IntegerField(help_text='Введіть кількість', max_length=12, verbose_name="Об'єм пакетних даних Мб/міс")),
                ('rate_volume', models.FloatField(help_text='Введіть суму', max_length=5, verbose_name='Тариф за 1Мб поза пакетом')),
                ('installer', models.CharField(choices=[('1', 'Герус В.'), ('2', 'Манін В.'), ('3', 'Ігнатенко М.')], help_text='Оберіть монтажника, якому видано сім', max_length=1, verbose_name='Монтажник')),
                ('date_given', models.DateField(help_text='Оберіть дату', verbose_name='Дата видачі монтажнику сім')),
            ],
        ),
    ]
