# Generated by Django 2.2.4 on 2020-03-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200311_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='products.Gps', verbose_name='БР'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_client',
            field=models.FloatField(help_text='Введіть суму', max_length=5, null=True, verbose_name='Тариф для клєнта грн/міс'),
        ),
    ]
