# Generated by Django 2.2.4 on 2020-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200315_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='packet_volume',
            field=models.PositiveIntegerField(blank=True, help_text='Введіть кількість', verbose_name="Об'єм пакетних даних Мб/міс"),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate',
            field=models.FloatField(blank=True, help_text='Введіть суму', max_length=5, verbose_name='Тариф грн/міс'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_volume',
            field=models.FloatField(blank=True, help_text='Введіть суму', max_length=5, verbose_name='Тариф за 1Мб поза пакетом'),
        ),
    ]
