# Generated by Django 2.2.4 on 2020-02-28 20:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_start_work',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прийому на роботу'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True, verbose_name='Номер телефону співробітника'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
    ]
