# Generated by Django 2.2.13 on 2021-01-26 17:20

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200315_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_2',
            field=models.EmailField(max_length=254, null=True, verbose_name='Персональна електронна адреса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Робоча електронна адреса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_2',
            field=phone_field.models.PhoneField(max_length=31, null=True, verbose_name='Персональний номер телефону співробітника'),
        ),
    ]
