# Generated by Django 2.2.13 on 2021-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210126_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Персональна електронна адреса'),
        ),
    ]
