# Generated by Django 2.2.13 on 2021-01-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_to_additions', to='contracts.Additions', verbose_name='ДУ до даного проекту'),
        ),
    ]
