# Generated by Django 2.2.13 on 2021-01-26 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 1, 26), verbose_name='Дата створення проекту'),
        ),
    ]
