# Generated by Django 2.2.13 on 2021-01-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pay_form',
        ),
    ]
