# Generated by Django 2.2.13 on 2021-01-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210126_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='invoice',
        ),
    ]
