# Generated by Django 2.2.13 on 2021-01-26 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210126_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата створення проекту'),
        ),
    ]
