# Generated by Django 2.2.13 on 2021-01-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_pay_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='invoices.ProjectInvoice', verbose_name='РФ/КО'),
        ),
    ]
