# Generated by Django 2.2.13 on 2021-02-04 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210126_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 2, 4), verbose_name='Дата створення проекту'),
        ),
    ]
