# Generated by Django 2.2.13 on 2021-02-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 2, 5), verbose_name='Дата створення проекту'),
        ),
    ]
