# Generated by Django 2.2.13 on 2021-02-25 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210205_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 2, 25), verbose_name='Дата створення проекту'),
        ),
    ]
