# Generated by Django 2.2.13 on 2021-02-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210225_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 2, 26), verbose_name='Дата створення проекту'),
        ),
    ]
