# Generated by Django 2.2.13 on 2021-02-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210226_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 2, 27), verbose_name='Дата створення проекту'),
        ),
    ]
