# Generated by Django 2.2.13 on 2021-03-04 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210303_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 3, 4), verbose_name='Дата створення проекту'),
        ),
    ]
