# Generated by Django 2.2.13 on 2021-04-17 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210304_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 17), verbose_name='Дата створення проекту'),
        ),
    ]
