# Generated by Django 2.2.20 on 2021-04-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210417_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='загальна сума проекту'),
        ),
    ]
