# Generated by Django 2.2.20 on 2021-04-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210417_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 20), verbose_name='Дата створення проекту'),
        ),
    ]
