# Generated by Django 2.2.20 on 2021-04-27 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20210424_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 27), verbose_name='Дата створення проекту'),
        ),
    ]
