# Generated by Django 2.2.20 on 2021-04-28 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20210427_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 28), verbose_name='Дата створення проекту'),
        ),
    ]
