# Generated by Django 2.2.20 on 2021-06-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210512_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 15), verbose_name='Дата створення проекту'),
        ),
    ]
