# Generated by Django 2.2.20 on 2021-08-04 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20210706_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 8, 4), verbose_name='Дата створення проекту'),
        ),
    ]
