# Generated by Django 2.2.20 on 2021-08-05 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_auto_20210805_1336'),
        ('projects', '0026_auto_20210804_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_receipt_contract',
        ),
        migrations.AddField(
            model_name='project',
            name='addition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_additions', to='contracts.Additions', verbose_name='Дод.угода'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_project_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contract', to='contracts.Contract', verbose_name='Договір'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 8, 5), verbose_name='Дата створення проекту'),
        ),
    ]
