# Generated by Django 2.2.20 on 2021-08-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20210806_2156'),
        ('projects', '0028_auto_20210806_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='invoices.ProjectInvoice', verbose_name='РФ/КО'),
        ),
    ]
