# Generated by Django 2.2.20 on 2021-08-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='invoices.ProjectInvoice', verbose_name='РФ'),
        ),
    ]
