# Generated by Django 2.2.20 on 2021-08-09 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210806_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 8, 9), verbose_name='Дата створення проекту'),
        ),
    ]
