# Generated by Django 2.2.20 on 2021-09-17 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210917_1636'),
        ('projects', '0031_auto_20210809_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_receipt_sale_invoice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='invoice',
        ),
        migrations.AddField(
            model_name='project',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Оберіть постачальника', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='clients.Provider', verbose_name='Постачальник'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 9, 17), verbose_name='Дата створення проекту'),
        ),
    ]
