# Generated by Django 2.2.20 on 2021-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20210917_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення проекту'),
        ),
    ]
