# Generated by Django 2.2.20 on 2021-09-18 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_project_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 9, 18), verbose_name='Дата створення'),
        ),
    ]
