# Generated by Django 2.2.20 on 2021-09-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20210918_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='provider',
            field=models.ForeignKey(help_text='Оберіть постачальника', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='clients.Provider', verbose_name='Постачальник'),
        ),
    ]
