# Generated by Django 2.2.13 on 2021-01-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Номер РФ', null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('invoice_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='сума до сплати')),
                ('status_payment', models.CharField(blank=True, choices=[('Сплачено', 'Сплачено'), ('НЕ сплачено', 'НЕ сплачено'), ('Частково сплачено', 'Частково сплачено')], default='НЕ сплачено', help_text='Оберіть статус оплати', max_length=100, verbose_name='Статус оплати')),
                ('sum_payment', models.PositiveIntegerField(blank=True, default=0, help_text='Ведіть суму, якщо оплата часткова', null=True, verbose_name='сума оплати')),
                ('date_payment', models.DateField(blank=True, help_text='Заповниться автоматично', null=True, verbose_name='Дата оплати')),
            ],
            options={
                'verbose_name_plural': 'рахунки за сервісні роботи ',
            },
        ),
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Invoice')),
                ('client', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name_plural': 'Проекти рахунки фактури ',
                'db_table': 'projectinvoice',
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='ProjectInvoiceTaxfree',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Invoice')),
            ],
            options={
                'verbose_name_plural': 'Касові Ордера (КО)',
                'db_table': 'projectinvoicetaxfree',
            },
            bases=('invoices.invoice',),
        ),
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Invoice')),
                ('provider', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Постачальник')),
                ('client', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name_plural': 'АП рахунки фактури ',
                'db_table': 'subinvoice',
            },
            bases=('invoices.invoice',),
        ),
    ]
