# Generated by Django 2.2.13 on 2021-01-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0068_delete_subinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Номер РФ', max_length=100, null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('invoice_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='сума до сплати')),
                ('status', models.CharField(blank=True, choices=[('Сплачено', 'Сплачено'), ('НЕ сплачено', 'НЕ сплачено'), ('Частково сплачено', 'Частково сплачено')], default='НЕ сплачено', help_text='Оберіть статус оплати', max_length=100, verbose_name='Статус оплати')),
                ('date_payment', models.DateField(blank=True, help_text='Заповниться автоматично', null=True, verbose_name='Дата оплати')),
            ],
        ),
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Invoice')),
                ('provider', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Постачальник')),
                ('client', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='subscription.Subscription', verbose_name='АП')),
            ],
            options={
                'verbose_name_plural': 'АП рахунки фактури ',
            },
            bases=('invoices.invoice',),
        ),
    ]
