# Generated by Django 2.2.13 on 2021-01-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectinvoice',
            table='projectinvoice',
        ),
        migrations.AlterModelTable(
            name='projectinvoicetaxfree',
            table='projectinvoicetaxfree',
        ),
        migrations.AlterModelTable(
            name='subinvoice',
            table='subinvoice',
        ),
    ]
