# Generated by Django 2.2.13 on 2021-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20210125_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinvoice',
            options={'verbose_name_plural': 'Проекти рахунки фактури та касові ордери '},
        ),
        migrations.RemoveField(
            model_name='projectinvoice',
            name='project',
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='name',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='РФ/КО'),
        ),
        migrations.DeleteModel(
            name='ProjectInvoiceTaxfree',
        ),
    ]
