# Generated by Django 2.2.13 on 2021-01-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20210123_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoice',
            name='provider',
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectinvoicetaxfree',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice_taxfree', to='projects.Project', verbose_name='Проект'),
        ),
    ]
