# Generated by Django 2.2.13 on 2021-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210126_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Номер', null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Номер', null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Номер', null=True, verbose_name='№'),
        ),
    ]
