# Generated by Django 2.2.13 on 2021-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210125_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoice',
            name='name',
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='pay_form',
            field=models.CharField(blank=True, choices=[('КО', 'КО'), ('РФ', 'РФ')], default='КО', help_text='Оберіть форму оплати', max_length=100, verbose_name='РФ/КО'),
        ),
    ]
