# Generated by Django 2.2.13 on 2021-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210126_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvoice',
            name='client',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт'),
        ),
    ]
