# Generated by Django 2.2.13 on 2021-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20210125_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoice',
            name='client',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(help_text='Номер', null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='number',
            field=models.PositiveIntegerField(help_text='Номер', null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='number',
            field=models.PositiveIntegerField(help_text='Номер', null=True, verbose_name='№'),
        ),
    ]
