# Generated by Django 2.2.13 on 2021-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20210125_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(default='№ не призначений', help_text='Номер', max_length=100, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='number',
            field=models.CharField(default='№ не призначений', help_text='Номер', max_length=100, null=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='number',
            field=models.CharField(default='№ не призначений', help_text='Номер', max_length=100, null=True, verbose_name='№'),
        ),
    ]
