# Generated by Django 2.2.13 on 2021-01-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20210126_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinvoice',
            options={'verbose_name_plural': 'рахунки фактури та касові ордери проекти'},
        ),
    ]
