# Generated by Django 2.2.13 on 2021-02-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20210126_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_workorder', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
    ]
