# Generated by Django 2.2.13 on 2021-03-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20210225_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='work_order',
            new_name='wo',
        ),
    ]
