# Generated by Django 2.2.13 on 2021-04-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20210303_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sum_payment',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ведіть суму', null=True, verbose_name='сума оплати'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='sum_payment',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ведіть суму', null=True, verbose_name='сума оплати'),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='sum_payment',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Ведіть суму', null=True, verbose_name='сума оплати'),
        ),
    ]
