# Generated by Django 2.2.20 on 2021-08-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20210420_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoice',
            name='project_to',
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='type',
            field=models.CharField(blank=True, choices=[('поставки', 'поставки'), ('сервісного обслуговування', 'сервісного обслуговування'), ('абонентського обслуговування', 'абонентського обслуговування')], default='поставки', help_text='Оберіть тип', max_length=100, null=True, verbose_name='Тип РФ'),
        ),
        migrations.AddField(
            model_name='subinvoice',
            name='type',
            field=models.CharField(blank=True, choices=[('поставки', 'поставки'), ('сервісного обслуговування', 'сервісного обслуговування'), ('абонентського обслуговування', 'абонентського обслуговування')], default='поставки', help_text='Оберіть тип', max_length=100, null=True, verbose_name='Тип РФ'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
