# Generated by Django 2.2.20 on 2021-08-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20210806_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subinvoice',
            name='subscription',
        ),
    ]
