# Generated by Django 2.2.20 on 2021-09-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20210917_1636'),
        ('subscription', '0005_auto_20210917_1636'),
        ('invoices', '0014_remove_subinvoice_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, help_text='Номер', null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('invoice_sum', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='сума до сплати')),
                ('status_payment', models.CharField(blank=True, choices=[('Сплачено', 'Сплачено'), ('НЕ сплачено', 'НЕ сплачено'), ('Частково сплачено', 'Частково сплачено')], default='НЕ сплачено', help_text='Оберіть статус оплати', max_length=100, verbose_name='Статус оплати')),
                ('sum_payment', models.PositiveIntegerField(blank=True, default=0, help_text='Ведіть суму', null=True, verbose_name='сума оплати')),
                ('date_payment', models.DateField(blank=True, help_text='Заповниться автоматично', null=True, verbose_name='Дата оплати')),
            ],
            options={
                'verbose_name_plural': 'рахунки на послуги',
            },
        ),
        migrations.AlterModelOptions(
            name='subinvoice',
            options={'verbose_name_plural': 'АП рахунки фактури'},
        ),
        migrations.RemoveField(
            model_name='projectinvoice',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subinvoice',
            name='type',
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='subinvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_invoice', to='subscription.Subscription', verbose_name='РФ'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='client',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='pay_form',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт'),
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, help_text='Номер', null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('status', models.CharField(choices=[('Створено', 'Створено'), ('В наявності', 'В наявності')], default='Створено', help_text='Оберіть статус договору', max_length=100, verbose_name='Статус')),
                ('status_date', models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleinvoice', to='invoices.ProjectInvoice', verbose_name='РФ')),
            ],
            options={
                'verbose_name_plural': 'Видаткові Накладні до проектів',
            },
        ),
    ]
