# Generated by Django 2.2.20 on 2021-09-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20210917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinvoice',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Оберіть дату оплати', null=True, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='pay_form',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Форма оплати'),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Оберіть дату оплати', null=True, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='subinvoice',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Оберіть дату оплати', null=True, verbose_name='Дата оплати'),
        ),
    ]
