# Generated by Django 2.2.20 on 2021-09-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_auto_20210918_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleinvoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='saleinvoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invoice', to='invoices.SaleInvoice', verbose_name='ВН'),
        ),
    ]
