# Generated by Django 2.2.4 on 2020-03-17 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_auto_20200303_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('1', 'Перший - січень/лютий/берзень'), ('2', 'Другий - квітень/травень/червень'), ('3', 'Третій - липень/серпень/вересень'), ('4', 'Четвертий - жовтень/листопад/грудень')], help_text='Оберіть оператора', max_length=1, verbose_name='Квартал')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clients.Client', verbose_name='Платник')),
            ],
        ),
    ]
