# Generated by Django 2.2.4 on 2020-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.CharField(choices=[('1', 'ТОВ "Системи Контролю Транспорту"'), ('2', 'ФОП Шевчук С.І.'), ('3', 'ФОП Дячук Л.В.'), ('4', 'БК/ІНШЕ')], help_text='Оберіть постачальника', max_length=1, null=True, verbose_name='Постачальник'),
        ),
    ]
