# Generated by Django 2.2.4 on 2020-03-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200317_1613'),
        ('clients', '0003_auto_20200303_1326'),
        ('subscription', '0002_subscription_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('1', 'Перший'), ('2', 'Другий'), ('3', 'Третій'), ('4', 'Четвертий')], help_text='Оберіть оператора', max_length=1, verbose_name='Квартал'),
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата листа')),
                ('action', models.CharField(choices=[('1', 'Видалення'), ('2', 'Зміна тарифу')], help_text='Оберіть дію', max_length=1, verbose_name='Дія')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='clients.Client', verbose_name='Покупець/Абонент')),
                ('gps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='products.Gps', verbose_name='БР')),
            ],
        ),
    ]
