# Generated by Django 2.2.13 on 2021-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210304_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='status',
            field=models.CharField(choices=[('оброблено', 'оброблено'), ('передано на обробку сервісний відділ', 'передано на обробку')], default='передано на обробку сервісний відділ', help_text='Оберіть статус "оброблено", якщо не потрібно більше ніяких дій з реєстратором на сервері', max_length=100, verbose_name='Статус'),
        ),
    ]
