# Generated by Django 2.2.4 on 2020-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20200320_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letters',
            options={'verbose_name_plural': 'Звернення/листи'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'АП звітність '},
        ),
        migrations.AddField(
            model_name='letters',
            name='new_rate',
            field=models.CharField(blank=True, choices=[('1', 'Україна'), ('2', 'Світ'), ('3', 'Пауза'), ('4', 'Власна сім')], help_text='Оберіть тариф на який змінюється', max_length=1, null=True, verbose_name='на тариф'),
        ),
        migrations.AddField(
            model_name='letters',
            name='old_rate',
            field=models.CharField(blank=True, choices=[('1', 'Україна'), ('2', 'Світ'), ('3', 'Пауза'), ('4', 'Власна сім')], help_text='Оберіть тариф який змінюється', max_length=1, null=True, verbose_name='з тарифу'),
        ),
    ]
