# Generated by Django 2.2.20 on 2021-09-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_remove_vehicle_gps'),
        ('subscription', '0004_subscription_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='invoice',
        ),
        migrations.AddField(
            model_name='letters',
            name='vehicle',
            field=models.ForeignKey(default=None, help_text='Оберіть ТЗ для зміни', on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='vehicle.Vehicle', verbose_name='БР'),
        ),
    ]
