# Generated by Django 2.2.4 on 2020-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200322_1604'),
        ('subscription', '0004_auto_20200320_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='gps',
        ),
        migrations.AddField(
            model_name='letters',
            name='gps',
            field=models.ManyToManyField(related_name='letters', to='products.Gps', verbose_name='БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('Перший', 'Перший'), ('Другий', 'Другий'), ('Третій', 'Третій'), ('Четвертий', 'Четвертий')], default='Другий', max_length=1, verbose_name='Квартал'),
        ),
    ]
