# Generated by Django 2.2.20 on 2021-09-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20210917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='vehicle',
            field=models.ForeignKey(default=None, help_text='Оберіть ТЗ для зміни', on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='vehicle.Vehicle', verbose_name='ТЗ'),
        ),
    ]
