# Generated by Django 2.2.4 on 2020-03-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20200322_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clients.Client', verbose_name='Платник'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('Перший', 'Перший'), ('Другий', 'Другий'), ('Третій', 'Третій'), ('Четвертий', 'Четвертий')], default='Другий', max_length=100, verbose_name='Квартал'),
        ),
    ]
