# Generated by Django 2.2.4 on 2020-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20200322_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='action',
            field=models.CharField(choices=[('Видалення', 'Видалення'), ('Зміна тарифу', 'Зміна тарифу')], help_text='Оберіть дію', max_length=1, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='new_rate',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф на який змінюється', max_length=1, null=True, verbose_name='на тариф'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='old_rate',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф який змінюється', max_length=1, null=True, verbose_name='з тарифу'),
        ),
    ]
