# Generated by Django 2.2.20 on 2021-09-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20210917_1747'),
        ('subscription', '0006_auto_20210918_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='new_owner',
            field=models.ForeignKey(blank=True, help_text='Оберіть клієнта від якого реєструється звернення', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_new_owner', to='clients.Client', verbose_name='Новий власник'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='action',
            field=models.CharField(choices=[('Видалення', 'Видалення'), ('Зміна тарифу', 'Зміна тарифу'), ('Зміна власника', 'Зміна власника')], help_text='Оберіть дію', max_length=100, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Оберіть клієнта від якого реєструється звернення', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='clients.Client', verbose_name='Абонент'),
        ),
    ]
