# Generated by Django 2.2.4 on 2020-04-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20200322_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('Перший', 'Перший'), ('Другий', 'Другий'), ('Третій', 'Третій'), ('Четвертий', 'Четвертий')], default='Оберіть квартал в ручну', max_length=100, verbose_name='Квартал'),
        ),
    ]
