# Generated by Django 2.2.4 on 2020-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20200401_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate_all',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Всього об'єктів"),
        ),
    ]
