# Generated by Django 2.2.4 on 2020-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_subscription_rate_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='vehicle_count',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Всього ТЗ'),
        ),
    ]
