# Generated by Django 2.2.4 on 2020-04-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription_vehicle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='vehicle_count',
        ),
    ]
