# Generated by Django 2.2.4 on 2020-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_remove_subscription_vehicle_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate_ukr',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Всього об'єктів"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('Перший', 'Перший'), ('Другий', 'Другий'), ('Третій', 'Третій'), ('Четвертий', 'Четвертий')], default='Третій', max_length=100, verbose_name='Квартал'),
        ),
    ]
