# Generated by Django 2.2.4 on 2020-06-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20200622_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate_own_sim',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Об'єкти Власна Сім"),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rate_pause',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Об'єкти Пауза"),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rate_world',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Об'єкти Світ"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ukr',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Об'єкти Ураїна"),
        ),
    ]
