# Generated by Django 2.2.4 on 2020-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20200622_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rate_ua_world',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Україна+Світ'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='new_rate',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Україна+Світ', 'Україна+Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф на який змінюється', max_length=1, null=True, verbose_name='на тариф'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='old_rate',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Україна+Світ', 'Україна+Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф який змінюється', max_length=1, null=True, verbose_name='з тарифу'),
        ),
    ]
