# Generated by Django 2.2.4 on 2020-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20200622_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='rate_all',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='rate_ukr',
        ),
        migrations.AddField(
            model_name='subscription',
            name='rate_ua',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Ураїна'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Власна Сім'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Пауза'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Світ'),
        ),
    ]
