# Generated by Django 2.2.4 on 2020-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_auto_20200622_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name="Вартість грн/міс'"),
        ),
    ]
