# Generated by Django 2.2.4 on 2020-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_auto_20200729_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Покупець/Абонент'),
        ),
    ]
