# Generated by Django 2.2.4 on 2020-07-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_auto_20200729_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='action',
            field=models.CharField(choices=[('Видалення', 'Видалення'), ('Зміна тарифу', 'Зміна тарифу')], help_text='Оберіть дію', max_length=100, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='new_rate',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Україна+Світ', 'Україна+Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф на який змінюється', max_length=100, null=True, verbose_name='на тариф'),
        ),
    ]
