# Generated by Django 2.2.4 on 2020-08-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200622_2019'),
        ('subscription', '0022_auto_20200729_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='gps',
        ),
        migrations.AddField(
            model_name='letters',
            name='gps',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='products.Gps', verbose_name='БР'),
        ),
    ]
