# Generated by Django 2.2.4 on 2020-08-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0023_auto_20200803_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='gps',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='products.Gps', verbose_name='БР'),
        ),
    ]
