# Generated by Django 2.2.4 on 2020-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0025_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_sum',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Вартість активації (грн)'),
        ),
    ]
