# Generated by Django 2.2.4 on 2020-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0029_auto_20200821_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Покупець/Абонент'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='gps',
            field=models.ForeignKey(default=None, help_text='Оберіть реєстратор для зміни', on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='products.Gps', verbose_name='БР'),
        ),
    ]
