# Generated by Django 2.2.4 on 2020-08-21 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0031_auto_20200821_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Оберіть клієнта від якого реєструється звернення', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Покупець/Абонент'),
        ),
    ]
