# Generated by Django 2.2.13 on 2020-08-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0032_auto_20200821_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Вводити нічого не потрібно поле заповниться автоматично', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Покупець/Абонент'),
        ),
    ]
