# Generated by Django 2.2.13 on 2020-08-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0035_auto_20200821_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Оберіть клієнта від якого реєструється звернення', max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='clients.Client', verbose_name='Покупець/Абонент'),
        ),
    ]
