# Generated by Django 2.2.13 on 2020-08-24 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0036_auto_20200824_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 24), help_text='Оберіть дату', null=True, verbose_name='Дата листа'),
        ),
    ]
