# Generated by Django 2.2.13 on 2020-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0037_subscription_date_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(auto_now_add=True, help_text='Оберіть дату', null=True, verbose_name='Дата створення'),
        ),
    ]
