# Generated by Django 2.2.13 on 2020-08-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0038_auto_20200824_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letters',
            old_name='date',
            new_name='date_letter',
        ),
    ]
