# Generated by Django 2.2.13 on 2020-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0039_auto_20200824_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='date_letter',
            field=models.DateField(auto_now_add=True, help_text='Оберіть дату', null=True, verbose_name='Дата листа'),
        ),
    ]
