# Generated by Django 2.2.13 on 2020-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0041_auto_20200824_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_init',
        ),
        migrations.AlterField(
            model_name='letters',
            name='date_letter',
            field=models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата листа'),
        ),
    ]
