# Generated by Django 2.2.13 on 2020-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0043_auto_20200824_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sum_payment',
            field=models.IntegerField(blank=True, default=0, help_text='Введть сумуб що сплатив клієнт', null=True, verbose_name='сплачено'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='all_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='all_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='all_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_1m',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/жов'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_2m',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/лист'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_3m',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/груд'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_quarter',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='нараховано'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='жов - Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='лист - Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='груд - Св'),
        ),
    ]
