# Generated by Django 2.2.13 on 2020-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0044_auto_20200824_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='sum_payment',
            field=models.IntegerField(blank=True, default=0, help_text='Введть суму, що сплатив клієнт', null=True, verbose_name='сплачено'),
        ),
    ]
