# Generated by Django 2.2.13 on 2020-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0045_auto_20200824_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_payment',
            field=models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_sum',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума активації'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_1m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/жов'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_2m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/лист'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_3m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/груд'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sum_payment',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Введть суму, що сплатив клієнт', null=True, verbose_name='сплачено'),
        ),
    ]
