# Generated by Django 2.2.13 on 2020-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0046_auto_20200824_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='all_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='all_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='all_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - БР'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_1m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/1 міс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_2m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/2 міс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_3m',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн/3 міс'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_own_sim_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - ВС'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_pause_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - П'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - Укр'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_ua_world_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - Укр+Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_1m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='1 міс - Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_2m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='2 міс - Св'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='rate_world_3m',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='3 міс - Св'),
        ),
    ]
