# Generated by Django 2.2.13 on 2020-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0047_auto_20200824_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sum_to_pay',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='залишок'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_quarter',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='нараховано'),
        ),
    ]
