# Generated by Django 2.2.13 on 2020-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0050_auto_20200825_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='quarter',
            field=models.CharField(choices=[('Перший', 'Перший'), ('Другий', 'Другий'), ('Третій', 'Третій'), ('Четвертий', 'Четвертий')], default='Перший', max_length=100, verbose_name='Квартал'),
        ),
    ]
