# Generated by Django 2.2.13 on 2020-08-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0051_auto_20200825_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='year',
            field=models.CharField(blank=True, help_text='Заповниться автоматично', max_length=10, null=True, verbose_name='Рік'),
        ),
    ]
