# Generated by Django 2.2.13 on 2020-09-25 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0052_subscription_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(default=datetime.date(2020, 9, 25), help_text='Дата заповниться автоматично', null=True, verbose_name='Дата створення'),
        ),
    ]
