# Generated by Django 2.2.13 on 2020-08-25 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0054_auto_20200825_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 15, 7, 28, 671286, tzinfo=utc), help_text='Дата заповниться автоматично', null=True, verbose_name='Дата створення'),
        ),
    ]
