# Generated by Django 2.2.13 on 2020-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0057_auto_20200825_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(auto_now_add=True, help_text='Дата заповниться автоматично', null=True, verbose_name='Дата створення'),
        ),
    ]
