# Generated by Django 2.2.13 on 2020-08-25 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0059_auto_20200825_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата заповниться автоматично', null=True, verbose_name='Дата створення'),
        ),
    ]
