# Generated by Django 2.2.13 on 2020-08-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0060_auto_20200825_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_init',
            field=models.DateField(auto_now_add=True, help_text='Дата заповниться автоматично', null=True, verbose_name='Дата створення'),
        ),
    ]
