# Generated by Django 2.2.13 on 2020-08-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0062_auto_20200826_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='rate_ua_world_1m',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='rate_ua_world_2m',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='rate_ua_world_3m',
        ),
    ]
