# Generated by Django 2.2.13 on 2020-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0063_auto_20200826_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activation',
            field=models.BooleanField(default=False, verbose_name='активація'),
        ),
    ]
