# Generated by Django 2.2.13 on 2020-10-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0064_auto_20200831_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт')),
                ('number', models.CharField(blank=True, help_text='Номер РФ', max_length=100, null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='subscription.Subscription', verbose_name='АП')),
            ],
            options={
                'verbose_name_plural': 'АП рахунки фактури ',
            },
        ),
    ]
