# Generated by Django 2.2.13 on 2020-11-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0066_invoice_invoice_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Постачальник')),
                ('client', models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Клієнт')),
                ('number', models.CharField(blank=True, help_text='Номер РФ', max_length=100, null=True, verbose_name='№')),
                ('date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата створення')),
                ('invoice_sum', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть суму рахунку', null=True, verbose_name='сума рахунку грн')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='subscription.Subscription', verbose_name='АП')),
            ],
            options={
                'verbose_name_plural': 'АП рахунки фактури ',
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
