# Generated by Django 2.2.13 on 2021-01-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0067_auto_20201118_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubInvoice',
        ),
    ]
