# Generated by Django 2.2.13 on 2021-01-23 20:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('name', models.CharField(max_length=50, verbose_name="І'мя")),
                ('position', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('birthday', models.DateField(verbose_name='Дата народженя')),
                ('day_start', models.DateField(verbose_name='Дата початку робти')),
                ('phone_1', phone_field.models.PhoneField(max_length=31, null=True, verbose_name='робочий № телефону')),
                ('phone_2', phone_field.models.PhoneField(max_length=31, null=True, verbose_name='персональний № телефону ')),
                ('email_1', models.EmailField(max_length=254, null=True, verbose_name='робоча електронна адреса')),
                ('email_2', models.EmailField(max_length=254, null=True, verbose_name='персональна електронна адреса')),
            ],
            options={
                'verbose_name_plural': 'Співробітники',
            },
        ),
    ]
