# Generated by Django 2.2.13 on 2021-01-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('поставки', 'поставки'), ('сервісного обслуговування', 'сервісного обслуговування'), ('абонентського обслуговування', 'абонентського обслуговування')], help_text='Оберіть тип', max_length=100, verbose_name='Тип договору')),
                ('provider', models.CharField(blank=True, choices=[('ТОВ "Системи Контролю Транспорту"', 'ТОВ "Системи Контролю Транспорту"'), ('ФОП Шевчук С.І.', 'ФОП Шевчук С.І.'), ('ФОП Дячук Л.В.', 'ФОП Дячук Л.В.'), ('ФОП Демченко К.Б.', 'ФОП Демченко К.Б.')], default='ТОВ "Системи Контролю Транспорту"', help_text='Оберіть постачальника', max_length=100, verbose_name='Постачальник')),
                ('number', models.IntegerField(help_text='Введіть номер договору', verbose_name='Номер договору')),
                ('contract_date', models.DateField(help_text='Оберіть дату', verbose_name='Дата заключеня договору')),
                ('status', models.CharField(choices=[('Створений', 'Створений'), ('Відправлений укрпоштою', 'Відправлений укрпоштою'), ('Відправлений НП', 'Відправлений НП'), ('Відправлений на електронну пошту', 'Відправлений на електронну пошту'), ('В наявності', 'В наявності')], default='Створений', help_text='Оберіть статус договору', max_length=100, verbose_name='Статус')),
                ('status_date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу')),
                ('contract_image', models.ImageField(blank=True, upload_to='images/contracts', verbose_name='Скан-копія')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.Client', verbose_name='Покупець/Абонент')),
            ],
            options={
                'verbose_name_plural': 'Договори',
            },
        ),
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер ДУ')),
                ('date', models.DateField(verbose_name='Дата заключеня ДУ')),
                ('status', models.CharField(choices=[('Створений', 'Створений'), ('Відправлений укрпоштою', 'Відправлений укрпоштою'), ('Відправлений НП', 'Відправлений НП'), ('Відправлений на електронну пошту', 'Відправлений на електронну пошту'), ('В наявності', 'В наявності')], default='Створений', help_text='Оберіть статус договору', max_length=100, verbose_name='Статус')),
                ('status_date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу')),
                ('contract_supp_image', models.ImageField(blank=True, upload_to='images/contracts', verbose_name='Скан-копія')),
                ('contract_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additions', to='contracts.Contract', verbose_name='Основний договір до якого створено ДУ')),
            ],
            options={
                'verbose_name_plural': 'Додаткові Угоди',
            },
        ),
    ]
