# Generated by Django 2.2.4 on 2020-02-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('1', 'Абонплата'), ('2', 'Поставки'), ('3', 'Обслуговування')], help_text='Оберіть тип договору', max_length=1, verbose_name='Тип договору')),
                ('provider', models.CharField(choices=[('1', 'ТОВ "Системи Контролю Транспорту"'), ('2', 'ФОП Шевчук С.І.'), ('3', 'ФОП Дячук Л.В.')], help_text='Оберіть постачальника', max_length=1, verbose_name='Постачальник')),
                ('number', models.IntegerField(help_text='Введіть номер договору', verbose_name='Номер договору')),
                ('contract_date', models.DateField(help_text='Оберіть дату', verbose_name='Дата заключеня договору')),
                ('status', models.CharField(choices=[('1', 'Створений'), ('2', 'Відправлений укрпоштою'), ('3', 'Відправлений НП'), ('4', 'Відправлений на електронну пошту'), ('5', 'В наявності')], help_text='Оберіть статус договору', max_length=1, verbose_name='Статус')),
                ('status_date', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата статусу(створення/відправки/отримання)')),
                ('contract_image', models.ImageField(blank=True, upload_to='images/contracts', verbose_name='Скан-копія')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.Client', verbose_name='Покупець/Абонент')),
            ],
            options={
                'verbose_name_plural': 'Договори',
            },
        ),
    ]
