# Generated by Django 2.2.13 on 2021-01-26 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210126_1247'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additions',
            old_name='contract_supp_image',
            new_name='contract_image',
        ),
        migrations.RemoveField(
            model_name='additions',
            name='date',
        ),
        migrations.AddField(
            model_name='additions',
            name='add_project_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_add_contract', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='additions',
            name='contract_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 12, 45, 2, 578009), help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_project_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contract', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='additions',
            name='number',
            field=models.IntegerField(help_text='Введіть номер договору', verbose_name='Номер Дог./ ДУ'),
        ),
        migrations.AlterField(
            model_name='additions',
            name='status_date',
            field=models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 26, 12, 45, 2, 578009), help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.IntegerField(help_text='Введіть номер договору', verbose_name='Номер Дог./ ДУ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status_date',
            field=models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу'),
        ),
    ]
