# Generated by Django 2.2.13 on 2021-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='provider',
            field=models.CharField(blank=True, choices=[('ТОВ "Системи Контролю Транспорту"', 'ТОВ "Системи Контролю Транспорту"'), ('ФОП Шевчук С.І.', 'ФОП Шевчук С.І.'), ('ФОП Дячук Л.В.', 'ФОП Дячук Л.В.'), ('ФОП Демченко К.Б.', 'ФОП Демченко К.Б.')], default='ТОВ "Системи Контролю Транспорту"', help_text='Оберіть постачальника', max_length=100, verbose_name='Постачальник'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Створений', 'Створений'), ('Відправлений укрпоштою', 'Відправлений укрпоштою'), ('Відправлений НП', 'Відправлений НП'), ('Відправлений на електронну пошту', 'Відправлений на електронну пошту'), ('В наявності', 'В наявності')], default='Створений', help_text='Оберіть статус договору', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, choices=[('поставки', 'поставки'), ('сервісного обслуговування', 'сервісного обслуговування'), ('абонентського обслуговування', 'абонентського обслуговування')], help_text='Оберіть тип', max_length=100, verbose_name='Тип договору'),
        ),
    ]
