# Generated by Django 2.2.4 on 2020-03-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractsupplementary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsupplementary',
            options={'verbose_name_plural': 'Додаткові Угоди'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='status_date',
            field=models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу'),
        ),
        migrations.AlterField(
            model_name='contractsupplementary',
            name='date',
            field=models.DateField(help_text='Оберіть дату', verbose_name='Дата заключеня ДУ'),
        ),
    ]
