# Generated by Django 2.2.13 on 2021-01-26 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210126_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
    ]
