# Generated by Django 2.2.13 on 2021-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='date',
            field=models.DateField(verbose_name='Дата заключеня ДУ'),
        ),
        migrations.AlterField(
            model_name='additions',
            name='number',
            field=models.IntegerField(verbose_name='Номер ДУ'),
        ),
    ]
