# Generated by Django 2.2.13 on 2021-01-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20200309_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsupplementary',
            name='contract_supp_image',
            field=models.ImageField(blank=True, upload_to='images/contracts', verbose_name='Скан-копія'),
        ),
        migrations.AddField(
            model_name='contractsupplementary',
            name='status',
            field=models.CharField(choices=[('1', 'Створений'), ('2', 'Відправлений укрпоштою'), ('3', 'Відправлений НП'), ('4', 'Відправлений на електронну пошту'), ('5', 'В наявності')], default='1', help_text='Оберіть статус договору', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='contractsupplementary',
            name='status_date',
            field=models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата зміни статусу'),
        ),
    ]
