# Generated by Django 2.2.13 on 2021-01-26 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210126_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 1, 26), help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 1, 26), help_text='Оберіть дату', verbose_name='Дата заключеня Дог./ ДУ'),
        ),
    ]
