# Generated by Django 2.2.13 on 2021-01-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210120_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('1', 'Створений'), ('2', 'Відправлений укрпоштою'), ('3', 'Відправлений НП'), ('4', 'Відправлений на електронну пошту'), ('5', 'В наявності')], default='1', help_text='Оберіть статус договору', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contractsupplementary',
            name='contract_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary', to='contracts.Contract', verbose_name='Основний договір до якого створюється ДУ'),
        ),
    ]
