# Generated by Django 2.2.13 on 2021-01-26 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210126_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 1, 26), help_text='Оберіть дату', verbose_name='Дата заключеня'),
        ),
        migrations.AlterField(
            model_name='additions',
            name='number',
            field=models.IntegerField(help_text='Введіть номер', verbose_name='Номер №'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 1, 26), help_text='Оберіть дату', verbose_name='Дата заключеня'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.IntegerField(help_text='Введіть номер', verbose_name='Номер №'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, choices=[('поставки', 'поставки'), ('сервісного обслуговування', 'сервісного обслуговування'), ('абонентського обслуговування', 'абонентського обслуговування')], default='поставки', help_text='Оберіть тип', max_length=100, verbose_name='Тип договору'),
        ),
    ]
