# Generated by Django 2.2.20 on 2021-08-05 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_auto_20210804_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additions',
            name='add_project_to',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_project_to',
        ),
        migrations.AlterField(
            model_name='additions',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 8, 5), help_text='Оберіть дату', verbose_name='Дата заключеня'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(default=datetime.date(2021, 8, 5), help_text='Оберіть дату', verbose_name='Дата заключеня'),
        ),
    ]
