# Generated by Django 2.2.4 on 2020-03-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': 'Транспортні засоби'},
        ),
    ]
