# Generated by Django 2.2.13 on 2021-03-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProxy',
        ),
        migrations.CreateModel(
            name='ClientProxyContracts',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Клієнт зведені дані по договорах',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='ClientProxyLetters',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Клієнт зведені дані по зверненнях',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='ClientProxyPayment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Клієнт зведені дані по оплатах',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='ClientProxyWorkOrders',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Клієнт зведені дані по роботах',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.client',),
        ),
    ]
