# Generated by Django 2.2.13 on 2021-03-04 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210303_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientProxyContracts',
        ),
        migrations.DeleteModel(
            name='ClientProxyLetters',
        ),
        migrations.DeleteModel(
            name='ClientProxyWorkOrders',
        ),
    ]
