# Generated by Django 2.2.4 on 2020-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200320_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.CharField(choices=[('1', 'ТОВ "Системи Контролю Транспорту"'), ('2', 'ФОП Шевчук С.І.'), ('3', 'ФОП Дячук Л.В.'), ('4', 'БК/ІНШЕ')], help_text='Оберіть постачальника з абонплати', max_length=1, null=True, verbose_name='Постачальник з абонплати'),
        ),
    ]
