# Generated by Django 2.2.20 on 2021-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210417_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='index',
            field=models.CharField(max_length=5, verbose_name='Пштовий індекс'),
        ),
    ]
