# Generated by Django 2.2.4 on 2020-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200322_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('1', 'активний'), ('2', 'видалений')], default='активний', help_text='Оберіть статус клієнта', max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
