# Generated by Django 2.2.20 on 2021-08-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210615_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть повну назву постачальника послуг', max_length=100, null=True, verbose_name='Назва')),
                ('tax_type', models.CharField(choices=[('без ПДВ', 'ез ПДВ'), ('з ПДВ', 'з ПДВ')], default='без ПДВ', help_text='Оберіть форму з ПДВ чи без', max_length=100, null=True, verbose_name='Форма оплати')),
            ],
            options={
                'verbose_name_plural': 'Постачальники послуг для клієнтів',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_provider', to='clients.Provider', verbose_name='Постачальник з АП'),
        ),
    ]
