# Generated by Django 2.2.20 on 2021-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210805_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='tax_type',
            field=models.CharField(choices=[('без ПДВ', 'без ПДВ'), ('з ПДВ', 'з ПДВ')], default='без ПДВ', help_text='Оберіть форму з ПДВ чи без', max_length=100, null=True, verbose_name='Форма оплати'),
        ),
    ]
