# Generated by Django 2.2.20 on 2021-09-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210806_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlegaldetail',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='legal_info',
            field=models.OneToOneField(blank=True, default=None, help_text='Оберіть або створіть реквізити', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_legal_detail', to='clients.ClientLegalDetail', verbose_name='Клієнт'),
        ),
    ]
