# Generated by Django 2.2.20 on 2021-09-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legal_info',
            field=models.OneToOneField(blank=True, default=None, help_text='Оберіть або створіть реквізити', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_legal_detail', to='clients.ClientLegalDetail', verbose_name='Реквізити'),
        ),
        migrations.AlterField(
            model_name='clientlegaldetail',
            name='bank',
            field=models.CharField(blank=True, help_text='Введіть назву банку', max_length=100, null=True, verbose_name='Банк'),
        ),
    ]
