# Generated by Django 2.2.13 on 2020-08-26 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20200826_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='edrpou',
            field=models.CharField(default=0, help_text='Введіть ЄДРПОУ клієнта', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,10}$'), django.core.validators.MinLengthValidator(8)], verbose_name='ЄДРПОУ'),
        ),
    ]
