# Generated by Django 2.2.13 on 2020-08-26 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20200826_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='IBAN',
            field=models.CharField(blank=True, default=12345678912345678901234567890, help_text='Введіть IBAN клієнта', max_length=29, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$'), django.core.validators.MinLengthValidator(29)], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='IPN',
            field=models.CharField(blank=True, default=123456789012, help_text='Введіть ІПН клієнта', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$'), django.core.validators.MinLengthValidator(10)], verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='edrpou',
            field=models.CharField(default=12345678, help_text='Введіть ЄДРПОУ клієнта', max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,10}$'), django.core.validators.MinLengthValidator(8)], verbose_name='ЄДРПОУ'),
        ),
    ]
