# Generated by Django 2.2.13 on 2020-08-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20200826_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notification_contact_1',
            field=models.ForeignKey(default=None, help_text='Оберіть контактну особу яку повідомлятимуть по рахунках', on_delete=django.db.models.deletion.CASCADE, related_name='client_notification_field_1', to='clients.ContactProfile', verbose_name='Контактна особи для повідомлень'),
        ),
        migrations.AddField(
            model_name='client',
            name='notification_contact_2',
            field=models.ForeignKey(blank=True, default=None, help_text='Оберіть контактну особу яку повідомлятимуть по рахунках', on_delete=django.db.models.deletion.CASCADE, related_name='client_notification_field_2', to='clients.ContactProfile', verbose_name='Контактна особи для повідомлень'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_notification_1',
            field=models.CharField(choices=[('SMS', 'SMS'), ('VIBER', 'VIBER'), ('Email', 'Email'), ('M.E.D.O.C.', 'M.E.D.O.C.'), ('Дзвінок', 'Дзвінок')], default='SMS', help_text='Оберіть спосіб повідомлення клієнта по рахунках', max_length=100, null=True, verbose_name='Тип повідомлень 1'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_notification_2',
            field=models.CharField(blank=True, choices=[('SMS', 'SMS'), ('VIBER', 'VIBER'), ('Email', 'Email'), ('M.E.D.O.C.', 'M.E.D.O.C.'), ('Дзвінок', 'Дзвінок')], default='SMS', help_text='Оберіть спосіб повідомлення клієнта по рахунках', max_length=100, null=True, verbose_name='Тип повідомлень 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_notification_contact_1',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='телфон/адреса'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_notification_contact_2',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='телфон/адреса'),
        ),
    ]
