# Generated by Django 2.2.13 on 2020-08-28 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20200827_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='IBAN',
        ),
        migrations.RemoveField(
            model_name='client',
            name='IPN',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='director',
        ),
        migrations.RenameModel(
            old_name='ClientPostAddress',
            new_name='ClientAddress',
        ),
        migrations.CreateModel(
            name='ClientLegalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPN', models.CharField(blank=True, default=123456789012, help_text='Введіть ІПН клієнта', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$'), django.core.validators.MinLengthValidator(10)], verbose_name='ІПН')),
                ('director', models.CharField(blank=True, help_text='Введіть ПІП директора', max_length=100, null=True, verbose_name='Директор')),
                ('IBAN', models.CharField(blank=True, default=12345678912345678901234567890, help_text='Введіть IBAN клієнта', max_length=29, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$'), django.core.validators.MinLengthValidator(29)], verbose_name='IBAN')),
                ('bank_account', models.CharField(blank=True, default=1234567890, help_text='Введіть р/р', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$')], verbose_name='№ р/р')),
                ('MFO', models.CharField(blank=True, default=12345, help_text='Введіть IBAN клієнта', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,100}$'), django.core.validators.MinLengthValidator(5)], verbose_name='IBAN')),
                ('bank', models.CharField(blank=True, help_text='Введіть назву банку', max_length=100, null=True, verbose_name='Банк>')),
                ('client', models.ForeignKey(blank=True, default=None, help_text='Оберіть клєнта якому належать ці реквізити', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_legal_detail', to='clients.Client', verbose_name='Клієнт')),
                ('legal_address', models.OneToOneField(blank=True, help_text='Оберіть юридичну адресу клієнта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_legal_address', to='clients.ClientAddress', verbose_name='Юридична адреса')),
                ('post_address', models.OneToOneField(blank=True, help_text='Оберіть поштову адресу клієнта, якщо вона не співпадає з юридичною', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_post_address', to='clients.ClientAddress', verbose_name='Поштова адреса')),
            ],
            options={
                'verbose_name_plural': 'Реквізити клієнтів',
            },
        ),
    ]
