# Generated by Django 2.2.13 on 2020-08-29 18:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20200828_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type_notification_contact_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_notification_contact_2',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_email_contact_1',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='телефон/адреса'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_email_contact_2',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='телефон/адреса'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='електронна адреса'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, null=True, verbose_name='№ телефону'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='phone_2',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='додатковий № телефону'),
        ),
    ]
