# Generated by Django 2.2.13 on 2021-01-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'Тягач'), ('2', 'Легкове авто'), ('3', 'Мікроавтобус'), ('4', 'Екскаватор'), ('5', 'Навантажувач'), ('6', 'Трактор'), ('7', 'Оприскувач'), ('8', 'Комбайн'), ('9', 'Асфальтоукладник'), ('10', 'Фреза'), ('11', 'Каток'), ('12', 'Інше')], help_text='Оберіть тип Транспортного Засобу', max_length=1, verbose_name='Тип ТЗ')),
                ('make', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Модель')),
                ('number', models.CharField(max_length=50, verbose_name=' Ідентифікатор (держ.номер)')),
            ],
            options={
                'verbose_name_plural': 'Транспортні засоби',
            },
        ),
    ]
