# Generated by Django 2.2.20 on 2021-08-04 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210615_1604'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='clients.Client', verbose_name='Власник'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_client',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rate_price',
            field=models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Вартість грн/міс'),
        ),
    ]
