# Generated by Django 2.2.4 on 2020-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200303_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(max_length=50, verbose_name=' Ідентифікатор (держ.номер)'),
        ),
    ]
