# Generated by Django 2.2.20 on 2021-08-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_gps_vehicle'),
        ('vehicle', '0002_auto_20210804_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='products.Gps', verbose_name='Транспортний засіб'),
        ),
    ]
