# Generated by Django 2.2.20 on 2021-08-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='products.Gps', verbose_name='БР'),
        ),
    ]
