# Generated by Django 2.2.20 on 2021-09-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20210805_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='gps',
        ),
    ]
