# Generated by Django 2.2.20 on 2021-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_remove_vehicle_gps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='rate_client',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім'), ('Персональний', 'Персональний')], help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф'),
        ),
    ]
