# Generated by Django 2.2.4 on 2020-02-26 16:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Номер телефону співробітника', max_length=31, null=True),
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
