# Generated by Django 2.2.4 on 2020-02-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPostAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Пштовий індекс')),
                ('region', models.CharField(help_text='Область', max_length=50)),
                ('district', models.CharField(help_text='Район', max_length=50)),
                ('city', models.CharField(help_text='Місто', max_length=50)),
                ('street', models.CharField(help_text='Вулиця', max_length=200)),
                ('house', models.CharField(help_text='Номер будинку', max_length=50)),
                ('office', models.CharField(help_text='Номер офісу або квартири', max_length=50)),
                ('client_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='clients.Client')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientPostAdress',
        ),
    ]
