# Generated by Django 2.2.4 on 2020-02-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=128, verbose_name="Ім'я користувача (login)"),
        ),
    ]
