# Generated by Django 2.2.4 on 2020-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200228_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pay_form',
        ),
        migrations.AddField(
            model_name='client',
            name='day_start',
            field=models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата початку роботи'),
        ),
    ]
