# Generated by Django 2.2.4 on 2020-02-26 17:02

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200225_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactphone',
            name='contact_profile',
        ),
        migrations.RenameField(
            model_name='clientpostaddress',
            old_name='client_profile',
            new_name='client',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='email',
            field=models.EmailField(help_text='Контактна електронна адреса', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Контактний номер телефону', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='phone_2',
            field=phone_field.models.PhoneField(help_text='додатковий контактний номер телефону', max_length=31, null=True),
        ),
        migrations.DeleteModel(
            name='ContactEmail',
        ),
        migrations.DeleteModel(
            name='ContactPhone',
        ),
    ]
