# Generated by Django 2.2.4 on 2020-02-27 09:31

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200226_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('1', 'активний'), ('2', 'видалений')], help_text='Оберіть статус клієнта', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='phone_2',
            field=phone_field.models.PhoneField(blank=True, help_text='додатковий контактний номер телефону', max_length=31, null=True),
        ),
    ]
