# Generated by Django 2.2.4 on 2020-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20200227_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='client_field',
        ),
        migrations.AddField(
            model_name='client',
            name='contacts',
            field=models.ManyToManyField(related_name='client_field', to='clients.ContactProfile'),
        ),
    ]
