# Generated by Django 2.2.4 on 2020-02-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200227_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpostaddress',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.ClientPostAddress'),
        ),
    ]
