# Generated by Django 2.2.13 on 2021-01-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProjectWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_works', to='vehicle.Vehicle', verbose_name='ТЗ')),
                ('fuel_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_service_works', to='products.FuelSensor', verbose_name='ДВРП')),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_service_works', to='products.Gps', verbose_name='БР')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_service_works', to='products.Service', verbose_name='виконані роботи')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введіть дату', verbose_name='Дата ЗН')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Номер PY', null=True, verbose_name='№')),
                ('type_of_work', models.CharField(choices=[('Проект', 'Проект'), ('Сервіс', 'Сервіс')], default='Проект', help_text='Оберіть тип', max_length=100, verbose_name='Тип ЗН (Проект/Серві')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.Project', verbose_name='№ проекту до якого відноситься ЗН')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedServiceWorks',
            fields=[
                ('completedprojectworks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workorders.CompletedProjectWorks')),
                ('payer', models.CharField(choices=[('Клієнт', 'Клієнт'), ('СКТ', 'ЛайСКТфсел'), ('монтажник', 'Тревел-монтажник'), ('виробник', 'виробник-сім')], default='Клієнт', help_text='Оберіть платника', max_length=100, verbose_name='Платник')),
                ('used_equipment', models.ManyToManyField(related_name='used_equipment', to='products.Equipment', verbose_name='використане обладнання')),
            ],
            options={
                'verbose_name_plural': 'Виконані сервісні роботи та використане обладнання',
            },
            bases=('workorders.completedprojectworks',),
        ),
    ]
