# Generated by Django 2.2.13 on 2021-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='info',
        ),
        migrations.AddField(
            model_name='completedworks',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='додаткова інформація з протоколу огляду'),
        ),
    ]
