# Generated by Django 2.2.13 on 2021-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name_plural': 'Заказ-Наряди'},
        ),
    ]
