# Generated by Django 2.2.13 on 2021-01-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedprojectworks',
            name='fuel_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_project_works', to='products.FuelSensor', verbose_name='ДВРП'),
        ),
        migrations.AlterField(
            model_name='completedprojectworks',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_project_works', to='products.Gps', verbose_name='БР'),
        ),
    ]
