# Generated by Django 2.2.13 on 2021-01-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_auto_20210125_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.Project', verbose_name='Проект'),
        ),
    ]
