# Generated by Django 2.2.13 on 2021-01-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_auto_20210125_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='виконавець'),
        ),
    ]
