# Generated by Django 2.2.13 on 2021-01-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('workorders', '0002_auto_20210124_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(choices=[('Клієнт', 'Клієнт'), ('СКТ', 'ЛайСКТфсел'), ('монтажник', 'Тревел-монтажник'), ('виробник', 'виробник-сім')], default='Клієнт', help_text='Оберіть платника', max_length=100, verbose_name='Платник')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_works', to='vehicle.Vehicle', verbose_name='ТЗ')),
                ('fuel_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_project_works', to='products.FuelSensor', verbose_name='ДВРП')),
                ('gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_project_works', to='products.Gps', verbose_name='БР')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to='products.Service', verbose_name='виконані роботи')),
                ('used_equipment', models.ManyToManyField(related_name='used_equipment', to='products.Equipment', verbose_name='використане обладнання')),
            ],
            options={
                'verbose_name_plural': 'Список виконаних робіт',
            },
        ),
        migrations.RemoveField(
            model_name='completedserviceworks',
            name='completedprojectworks_ptr',
        ),
        migrations.RemoveField(
            model_name='completedserviceworks',
            name='used_equipment',
        ),
        migrations.RemoveField(
            model_name='completedserviceworks',
            name='work_order_service',
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name_plural': 'Зака-Наряди'},
        ),
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_client',
            field=models.PositiveIntegerField(blank=True, help_text='Вартість додаткових витрат для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за ДВ \nклієнту'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_executor',
            field=models.PositiveIntegerField(blank=True, help_text='Сума коомпенсації за додаткові витрати монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за ДВ \nмонтажнику'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='month_executor_pay',
            field=models.DateField(help_text='місяць нарахування ЗП монтажнику', verbose_name='місяць/рік ЗП'),
        ),
        migrations.DeleteModel(
            name='CompletedProjectWorks',
        ),
        migrations.DeleteModel(
            name='CompletedServiceWorks',
        ),
        migrations.AddField(
            model_name='completedworks',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_works', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
    ]
