# Generated by Django 2.2.13 on 2021-01-26 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0003_auto_20210126_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='виконавець'),
        ),
    ]
