# Generated by Django 2.2.13 on 2021-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorder_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='amount_fuel_sensor',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='введіть кількість ТІЛЬКИ ЯКЩО ПРОЕКТ', null=True, verbose_name='кіл-ть ДВРП'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='amount_gps',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='введіть кількість ТІЛЬКИ ЯКЩО ПРОЕКТ', null=True, verbose_name='кіл-ть СКТ'),
        ),
    ]
