# Generated by Django 2.2.20 on 2021-08-09 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_auto_20210806_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 8, 9), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
