# Generated by Django 2.2.20 on 2021-09-17 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210917_1636'),
        ('invoices', '0015_auto_20210917_1636'),
        ('projects', '0032_auto_20210917_1636'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0005_auto_20210809_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введіть дату', verbose_name='Дата ЗН')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Номер ЗН', null=True, verbose_name='№')),
                ('price_of_completed_works', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума за виконані роботи')),
                ('price_of_used_equipment', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума за використане обладнання')),
                ('pay_form', models.CharField(blank=True, choices=[('КО', 'КО'), ('РФ', 'РФ')], default='КО', help_text='Оберіть форму оплати', max_length=100, verbose_name='Форма оплати')),
                ('milege', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='пробіг (км)')),
                ('milege_price_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км монтажнику')),
                ('milege_price_client', models.IntegerField(blank=True, default=0, help_text='Вартість пробігу для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км клієнту')),
                ('trip_day', models.FloatField(blank=True, default=0, help_text='Кількість днів нарахування добових монтажнику', null=True, verbose_name='Добові дні')),
                ('trip_day_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн добових \nмонтажнику')),
                ('add_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації за додаткові витрати монтажнику', null=True, verbose_name='грн за ДВ \nмонтажнику')),
                ('add_costs_client', models.IntegerField(blank=True, default=0, help_text='Вартість додаткових витрат для клієнта', null=True, verbose_name='грн за ДВ \nклієнту')),
                ('description_add_costs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список додаткових витрат')),
                ('month_executor_pay', models.DateField(blank=True, help_text='оберіть будь-яку дату в межах місяця нарахування ЗП монтажнику', null=True, verbose_name='місяць/рік ЗП')),
                ('sum_price_client', models.PositiveIntegerField(blank=True, default=0, help_text='сума рахунку для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума рахунку')),
                ('wo_image', models.ImageField(blank=True, upload_to='images/workorders', verbose_name='Скан-копія')),
                ('amount_gps', models.PositiveIntegerField(blank=True, default=0, help_text='введіть кількість', null=True, verbose_name='кіл-ть СКТ')),
                ('amount_fuel_sensor', models.PositiveIntegerField(blank=True, default=0, help_text='введіть кількість', null=True, verbose_name='кіл-ть ДВРП')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders_projectworkorder', to='clients.Client', verbose_name='клієнт')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders_projectworkorder', to=settings.AUTH_USER_MODEL, verbose_name='виконавець')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name_plural': 'Проектні заказ-наряди',
            },
        ),
        migrations.CreateModel(
            name='ServiceWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введіть дату', verbose_name='Дата ЗН')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Номер ЗН', null=True, verbose_name='№')),
                ('price_of_completed_works', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума за виконані роботи')),
                ('price_of_used_equipment', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума за використане обладнання')),
                ('pay_form', models.CharField(blank=True, choices=[('КО', 'КО'), ('РФ', 'РФ')], default='КО', help_text='Оберіть форму оплати', max_length=100, verbose_name='Форма оплати')),
                ('milege', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='пробіг (км)')),
                ('milege_price_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км монтажнику')),
                ('milege_price_client', models.IntegerField(blank=True, default=0, help_text='Вартість пробігу для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км клієнту')),
                ('trip_day', models.FloatField(blank=True, default=0, help_text='Кількість днів нарахування добових монтажнику', null=True, verbose_name='Добові дні')),
                ('trip_day_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн добових \nмонтажнику')),
                ('add_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації за додаткові витрати монтажнику', null=True, verbose_name='грн за ДВ \nмонтажнику')),
                ('add_costs_client', models.IntegerField(blank=True, default=0, help_text='Вартість додаткових витрат для клієнта', null=True, verbose_name='грн за ДВ \nклієнту')),
                ('description_add_costs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список додаткових витрат')),
                ('month_executor_pay', models.DateField(blank=True, help_text='оберіть будь-яку дату в межах місяця нарахування ЗП монтажнику', null=True, verbose_name='місяць/рік ЗП')),
                ('sum_price_client', models.PositiveIntegerField(blank=True, default=0, help_text='сума рахунку для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума рахунку')),
                ('wo_image', models.ImageField(blank=True, upload_to='images/workorders', verbose_name='Скан-копія')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders_serviceworkorder', to='clients.Client', verbose_name='клієнт')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders_serviceworkorder', to=settings.AUTH_USER_MODEL, verbose_name='виконавець')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_work_order', to='invoices.ServiceInvoice', verbose_name='РФ')),
            ],
            options={
                'verbose_name_plural': 'ЗН на сервісні роботи',
            },
        ),
        migrations.RemoveField(
            model_name='executorpayment',
            name='executor_1',
        ),
        migrations.RemoveField(
            model_name='executorpayment',
            name='executor_2',
        ),
        migrations.RemoveField(
            model_name='executorpayment',
            name='executor_3',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='project',
        ),
        migrations.DeleteModel(
            name='ExecutorPaymentProxy',
        ),
        migrations.DeleteModel(
            name='WorkOrderProxy',
        ),
        migrations.AlterField(
            model_name='completedworks',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_works', to='workorders.ServiceWorkOrder', verbose_name='ЗН'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 9, 17), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='ExpertiseWorkOrder',
            fields=[
                ('serviceworkorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workorders.ServiceWorkOrder')),
            ],
            options={
                'verbose_name_plural': 'ЗН на сервісні роботи (експертизи)',
            },
            bases=('workorders.serviceworkorder',),
        ),
        migrations.DeleteModel(
            name='ExecutorPayment',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
