# Generated by Django 2.2.13 on 2021-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_auto_20210126_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_client',
            field=models.PositiveIntegerField(blank=True, help_text='Вартість додаткових витрат для клієнта', null=True, verbose_name='грн за ДВ \nклієнту'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_executor',
            field=models.PositiveIntegerField(blank=True, help_text='Сума коомпенсації за додаткові витрати монтажнику', null=True, verbose_name='грн за ДВ \nмонтажнику'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='milege',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='пробіг (км)'),
        ),
    ]
