# Generated by Django 2.2.20 on 2021-09-18 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_auto_20210917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 9, 18), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
