# Generated by Django 2.2.13 on 2021-02-04 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0006_auto_20210204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedworks',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='додаткова інформація\nз протоколу огляду'),
        ),
        migrations.AlterField(
            model_name='completedworks',
            name='used_equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='used_equipment', to='products.Equipment', verbose_name='використане обладнання'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type_of_work',
            field=models.CharField(choices=[('Проект', 'Проект'), ('Сервіс', 'Сервіс')], default='Проект', help_text='Оберіть тип', max_length=100, verbose_name='Тип ЗН (Проект/Сервіc)'),
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=datetime.date(2021, 2, 4), help_text='Введіть дату', verbose_name='Дата')),
                ('type_of_service', models.CharField(choices=[('монтаж', 'монтаж'), ('демонтаж', 'демонтаж'), ('демонтаж+монтаж', 'демонтаж+монтаж'), ('отправка', 'отправка'), ('ремонт', 'ремонт'), ('демонтаж+ремонт', 'демонтаж+ремонт'), ('монтаж+ремонт', 'монтаж+ремонт')], help_text='Оберіть тип', max_length=100, verbose_name='Тип робіт')),
                ('city', models.CharField(blank=True, choices=[('Київ', 'Київ'), ('Вінниця', 'Вінниця'), ('Луцьк', 'Луцьк'), ('Дніпро', 'Дніпро'), ('Житомир', 'Житомир'), ('Ужгород', 'Ужгород'), ('Запоріжжя', 'Запоріжжя'), ('Івано-Франківськ', 'Івано-Франківськ'), ('Кропивницький', 'Кропивницький'), ('Львів', 'Львів'), ('Миколаїв', 'Миколаїв'), ('Одеса', 'Одеса'), ('Полтава', 'Полтава'), ('Суми', 'Суми'), ('Рівне', 'Рівне'), ('Тернопіль', 'Тернопіль'), ('Харків', 'Харків'), ('Херсон', 'Херсон'), ('Хмельницький', 'Хмельницький'), ('Черкаси', 'Черкаси'), ('Чернігів', 'Чернігів'), ('Чернівці', 'Чернівці')], help_text='Оберіть місто', max_length=100, null=True, verbose_name='місто')),
                ('district', models.CharField(blank=True, choices=[('Київська', 'Київська'), ('Вінницька', 'Вінницька'), ('Волинська', 'Волинська'), ('Дніпропетровьска', 'Дніпропетровьска'), ('Житомирська', 'Житомирська'), ('Закарпатська', 'Закарпатська'), ('Запоріжська', 'Запоріжська'), ('Івано-Франківська', 'Івано-Франківська'), ('Кіровоградська', 'Кіровоградська'), ('Львівська', 'Львівська'), ('Миколаївська', 'Миколаївська'), ('Одеська', 'Одеська'), ('Полтавська', 'Полтавська'), ('Рівненська', 'Рівненська'), ('Сумська', 'Сумська'), ('Тернопільська', 'Тернопільська'), ('Харківська', 'Харківська'), ('Херсонська', 'Херсонська'), ('Хмельницька', 'Хмельницька'), ('Черкаська', 'Черкаська'), ('Чернігівська', 'Чернігівська'), ('Чернівецька', 'Чернівецька')], help_text='Оберіть область', max_length=100, null=True, verbose_name='область')),
                ('type_of_delivery', models.CharField(choices=[('власний автомобіль', 'власний автомобіль'), ('силами замовника', 'силами замовника'), ('перевізник', 'перевізник')], max_length=100, null=True, verbose_name='Спосіб проїду')),
                ('tasks', models.CharField(help_text='Опишіть перелік запланованих робіт', max_length=100, null=True, verbose_name='Задачі')),
                ('date_planing', models.DateField(help_text='Введіть дату', verbose_name='Строк з / Дата')),
                ('time', models.CharField(help_text='Введіть дату або час вручну', max_length=100, verbose_name='Строк до / Час')),
                ('adress', models.CharField(max_length=100, null=True, verbose_name='Адреса')),
                ('wo_numb', models.PositiveIntegerField(blank=True, help_text='Номер ЗН', null=True, verbose_name='№')),
                ('date_ex', models.DateField(blank=True, help_text='Введіть дату', verbose_name='Дата виконання')),
                ('status', models.CharField(choices=[('виконано', 'виконано'), ('перенесено', 'перенесено')], max_length=100, null=True, verbose_name='Статус виконання')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders_plan', to='clients.Client', verbose_name='клієнт')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_plan_contact', to='clients.ContactProfile', verbose_name='Контактна особа')),
                ('contact_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_plan_contact_2', to='clients.ContactProfile', verbose_name='Дод. контактна особа')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders_plan_ex', to=settings.AUTH_USER_MODEL, verbose_name='виконавець')),
                ('respons_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_plan_response', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний менеджер')),
            ],
        ),
    ]
