# Generated by Django 2.2.13 on 2021-02-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_auto_20210204_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 2, 5), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
