# Generated by Django 2.2.20 on 2021-09-21 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20210921_1605'),
        ('clients', '0010_auto_20210917_1747'),
        ('products', '0010_auto_20210921_1605'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0006_auto_20210918_1444'),
        ('workorders', '0007_auto_20210918_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_works', models.CharField(blank=True, choices=[('Проектні', 'Проектні'), ('Сервісні', 'Сервісні'), ('Сервісні', 'Експертиза')], default='Проектні', help_text='Вкажіть куди віднести витрати до проекту чи до сервісних робіт', max_length=100, verbose_name='Тип додаткових витрат')),
                ('pay_form', models.CharField(blank=True, choices=[('КО', 'КО'), ('РФ', 'РФ')], default='КО', help_text='Оберіть форму оплати', max_length=100, verbose_name='Форма оплати')),
                ('milege', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='пробіг (км)')),
                ('milege_price_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км монтажнику')),
                ('milege_price_client', models.IntegerField(blank=True, default=0, help_text='Вартість пробігу для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км клієнту')),
                ('trip_day', models.FloatField(blank=True, default=0, help_text='Кількість днів нарахування добових монтажнику', null=True, verbose_name='Добові дні')),
                ('trip_day_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн добових \nмонтажнику')),
                ('add_costs_executor', models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації за додаткові витрати монтажнику', null=True, verbose_name='грн за ДВ \nмонтажнику')),
                ('add_costs_client', models.IntegerField(blank=True, default=0, help_text='Вартість додаткових витрат для клієнта', null=True, verbose_name='грн за ДВ \nклієнту')),
                ('description_add_costs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Список додаткових витрат')),
                ('month_executor_pay', models.DateField(blank=True, help_text='оберіть будь-яку дату в межах місяця нарахування ЗП монтажнику', null=True, verbose_name='місяць/рік ЗП')),
                ('sum_price_client', models.PositiveIntegerField(blank=True, default=0, help_text='*для клієнта \nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума додаткових витрат')),
            ],
            options={
                'verbose_name_plural': 'Додаткові витрати клієнтів',
            },
        ),
        migrations.CreateModel(
            name='CompletedProjectWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_gps', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='встановлено СКТ')),
                ('count_fuel', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='встановлено ДВРП')),
                ('fuel_sensor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_1_project_works', to='products.FuelSensor', verbose_name='ДВРП 1')),
                ('fuel_sensor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_2_project_works', to='products.FuelSensor', verbose_name='ДВРП 2')),
                ('gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_project_works', to='products.Gps', verbose_name='БР')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_completed_works', to='projects.Project', verbose_name='Проект')),
                ('type_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_completed_works', to='products.Service', verbose_name='Роботи які виконані')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_completed_works', to='vehicle.Vehicle', verbose_name='ТЗ')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedServiceWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(choices=[('Клієнт', 'Клієнт'), ('Експертиза', 'Експертиза'), ('СКТ', 'СКТ'), ('монтажник', 'монтажник'), ('виробник', 'виробник')], default='Клієнт', help_text='Оберіть платника', max_length=100, verbose_name='Платник')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='додаткова інформація\nз протоколу огляду')),
                ('fuel_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_service_works', to='products.FuelSensor', verbose_name='ДВРП')),
                ('gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_service_works', to='products.Gps', verbose_name='БР')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_works', to='products.Service', verbose_name='виконані роботи')),
                ('used_equipment', models.ManyToManyField(blank=True, null=True, related_name='used_equipment', to='products.Equipment', verbose_name='використане обладнання')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_works', to='vehicle.Vehicle', verbose_name='ТЗ')),
            ],
            options={
                'verbose_name_plural': 'Список виконаних робіт',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введіть дату', verbose_name='Дата ЗН')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Номер ЗН', null=True, verbose_name='№')),
                ('price_of_project_completed_works', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума за проектні виконані роботи')),
                ('price_of_service_completed_works', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума за сервісні виконані роботи')),
                ('price_of_expertise_completed_works', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума по результатах експертизи')),
                ('wo_image', models.ImageField(blank=True, upload_to='images/workorders', verbose_name='Скан-копія')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='clients.Client', verbose_name='клієнт')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to=settings.AUTH_USER_MODEL, verbose_name='виконавець')),
            ],
            options={
                'verbose_name_plural': 'Заказ Наряди',
            },
        ),
        migrations.RemoveField(
            model_name='expertiseworkorder',
            name='serviceworkorder_ptr',
        ),
        migrations.RemoveField(
            model_name='projectworkorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projectworkorder',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='projectworkorder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='serviceworkorder',
            name='invoice',
        ),
        migrations.RenameField(
            model_name='expertise',
            old_name='date_receving_expertise',
            new_name='date_receiving_expertise',
        ),
        migrations.RenameField(
            model_name='expertise',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='expertise',
            name='date_wo',
            field=models.CharField(help_text='Заповнюється автоматично з ЗН', max_length=200, verbose_name='Дата демонтажу (ЗН)'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 9, 21), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.DeleteModel(
            name='CompletedWorks',
        ),
        migrations.DeleteModel(
            name='ExpertiseWorkOrder',
        ),
        migrations.DeleteModel(
            name='ProjectWorkOrder',
        ),
        migrations.DeleteModel(
            name='ServiceWorkOrder',
        ),
        migrations.AddField(
            model_name='completedserviceworks',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_works', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='completedprojectworks',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_project_works', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='addcosts',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_costs', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='workorders.WorkOrder', verbose_name='ЗН'),
        ),
    ]
