# Generated by Django 2.2.20 on 2021-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_auto_20210921_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedprojectworks',
            options={'verbose_name_plural': 'Список виконаних проектних робіт'},
        ),
        migrations.AddField(
            model_name='completedprojectworks',
            name='count_executor_works',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Заповнюється автоматично', null=True, verbose_name='к-сть робыт, виконаних монтажником'),
        ),
        migrations.AlterField(
            model_name='completedprojectworks',
            name='count_fuel',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Заповнюється автоматично', null=True, verbose_name='встановлено ДВРП'),
        ),
        migrations.AlterField(
            model_name='completedprojectworks',
            name='count_gps',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Заповнюється автоматично', null=True, verbose_name='встановлено СКТ'),
        ),
    ]
