# Generated by Django 2.2.13 on 2021-02-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_auto_20210205_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'verbose_name_plural': 'План сервісних робіт'},
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='status',
            field=models.CharField(blank=True, choices=[('виконано', 'виконано'), ('перенесено', 'перенесено')], max_length=100, null=True, verbose_name='Статус виконання'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='tasks',
            field=models.CharField(help_text='Опишіть перелік запланованих робіт', max_length=1000, null=True, verbose_name='Задачі'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='type_of_delivery',
            field=models.CharField(choices=[('власний автомобіль', 'власний автомобіль'), ('силами замовника', 'силами замовника'), ('перевізник', 'перевізник')], default='власний автомобіль', max_length=100, null=True, verbose_name='Спосіб проїду'),
        ),
    ]
