# Generated by Django 2.2.13 on 2021-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_auto_20210205_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_ex',
            field=models.DateField(blank=True, help_text='Введіть дату', null=True, verbose_name='Дата виконання'),
        ),
    ]
