# Generated by Django 2.2.13 on 2021-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_auto_20210205_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='tasks',
            field=models.TextField(help_text='Опишіть перелік запланованих робіт', max_length=1000, null=True, verbose_name='Задачі'),
        ),
    ]
