# Generated by Django 2.2.13 on 2021-02-25 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_auto_20210205_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 2, 25), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='respons_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_plan_response', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний'),
        ),
    ]
