# Generated by Django 2.2.13 on 2021-02-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0013_auto_20210225_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 2, 26), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
