# Generated by Django 2.2.13 on 2021-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_auto_20210226_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='type_of_work',
            field=models.CharField(choices=[('Проект', 'Проект'), ('Сервіс', 'Сервіс')], default='Сервіс', help_text='Оберіть тип', max_length=100, verbose_name='Тип ЗН (Проект/Сервіc)'),
        ),
    ]
