# Generated by Django 2.2.13 on 2021-02-27 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0015_auto_20210226_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 2, 27), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
