# Generated by Django 2.2.13 on 2021-03-03 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0016_auto_20210227_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 3, 3), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
