# Generated by Django 2.2.13 on 2021-03-04 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0017_auto_20210303_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 3, 4), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
