# Generated by Django 2.2.13 on 2021-04-17 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_auto_20210304_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 17), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='pay_form',
            field=models.CharField(blank=True, choices=[('КО', 'КО'), ('РФ', 'РФ')], default='КО', help_text='Оберіть форму оплати', max_length=100, verbose_name='Форма оплати'),
        ),
    ]
