# Generated by Django 2.2.20 on 2021-04-21 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20210417_1314'),
        ('products', '0006_auto_20210304_1405'),
        ('workorders', '0020_auto_20210420_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedworks',
            name='payer',
            field=models.CharField(choices=[('Клієнт', 'Клієнт'), ('Експертиза', 'Експертиза'), ('СКТ', 'СКТ'), ('монтажник', 'монтажник'), ('виробник', 'виробник')], default='Клієнт', help_text='Оберіть платника', max_length=100, verbose_name='Платник'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 21), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_wo', models.DateField(help_text='Введіть дату', verbose_name='Дата демонтажу (ЗН)')),
                ('desription', models.CharField(blank=True, max_length=200, null=True, verbose_name='опис рекламації')),
                ('date_take_to_rapeir', models.DateField(help_text='Введіть дату', verbose_name='Дата сдачі в ремонт')),
                ('date_receving_expertise', models.DateField(help_text='Введіть дату', verbose_name='Дата отримання результатів експертизи (обладанання)')),
                ('malfunctions', models.CharField(blank=True, max_length=200, null=True, verbose_name='виявлені несправності')),
                ('result_expertise', models.CharField(blank=True, max_length=200, null=True, verbose_name='результати експертизи')),
                ('price_expertise', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вартість робіт')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='clients.Client', verbose_name='клієнт')),
                ('fuel_sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor_expertise', to='products.FuelSensor', verbose_name='ДВРП')),
                ('gps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_expertise', to='products.Gps', verbose_name='БР')),
            ],
            options={
                'verbose_name_plural': 'Експертизи',
            },
        ),
    ]
