# Generated by Django 2.2.20 on 2021-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0021_auto_20210421_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='date_receving_expertise',
            field=models.DateField(blank=True, help_text='Введіть дату', null=True, verbose_name='Дата отримання результатів експертизи (обладанання)'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='date_take_to_rapeir',
            field=models.DateField(blank=True, help_text='Введіть дату', null=True, verbose_name='Дата сдачі в ремонт'),
        ),
    ]
