# Generated by Django 2.2.20 on 2021-04-22 17:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorders', '0022_auto_20210421_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 22), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='ExecutorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days_1', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів(окрім вихідних)\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д. співробітник 1')),
                ('work_days_2', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів(окрім вихідних)\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д. співробітник 2')),
                ('work_days_3', models.PositiveIntegerField(blank=True, help_text='кількість робочих днів(окрім вихідних)\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д. співробітник 3')),
                ('work_days_sum', models.PositiveIntegerField(blank=True, help_text='кількість робочих днів(окрім вихідних)\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д. сумарно')),
                ('work_days_weekend_1', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів у вихідних\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д.вих співробітник 1')),
                ('work_days_weekend_2', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів у вихідних\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д.вих співробітник 1')),
                ('work_days_weekend_3', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів у вихідних\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д.вих співробітник 1')),
                ('work_days_weekend_sum', models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів у вихідних\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='роб.д.вих сумарно')),
                ('trip_day_1', models.PositiveIntegerField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові співробітник 1')),
                ('trip_day_2', models.PositiveIntegerField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові співробітник 2')),
                ('trip_day_3', models.PositiveIntegerField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові співробітник 3')),
                ('trip_day_sum', models.PositiveIntegerField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові сумарно')),
                ('qua_work_orders_1', models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть ЗН співробітник 1')),
                ('qua_work_orders_2', models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть ЗН співробітник 2')),
                ('qua_work_orders_3', models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть ЗН співробітник 3')),
                ('qua_work_orders_sum', models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть ЗН сумарно')),
                ('qua_works_1', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть вик. робіт співробітник 1')),
                ('qua_works_2', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть вик. робіт співробітник 2')),
                ('qua_works_3', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть вик. робіт співробітник 3')),
                ('qua_works_sum', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть вик. робіт сумарно')),
                ('qua_payment_works_1', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума ЗП співробітник 1')),
                ('qua_payment_works_2', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума ЗП співробітник 2')),
                ('qua_payment_works_3', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума ЗП співробітник 3')),
                ('qua_payment_works_sum', models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума ЗП сумарно')),
                ('milege_price_1', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км співробітник 1')),
                ('milege_price_2', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км співробітник 2')),
                ('milege_price_3', models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км співробітник 3')),
                ('premium_sum', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума премії')),
                ('boss_premium', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума премії керівника')),
                ('prmium_1', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума премії співробітник 1')),
                ('prmium_2', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума премії співробітник 2')),
                ('prmium_3', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума премії співробітник 3')),
                ('total_payment_1', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='загальна сума ЗП співробітник 1')),
                ('total_payment_2', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='загальна сума ЗП співробітник 1')),
                ('total_payment_3', models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='загальна сума ЗП співробітник 1')),
                ('executor_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_payment_1', to=settings.AUTH_USER_MODEL, verbose_name='співробітник 1')),
                ('executor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_payment_2', to=settings.AUTH_USER_MODEL, verbose_name='співробітник 2')),
                ('executor_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_payment_3', to=settings.AUTH_USER_MODEL, verbose_name='співробітник 3')),
            ],
        ),
    ]
