# Generated by Django 2.2.20 on 2021-04-23 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0023_auto_20210422_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorpayment',
            options={'verbose_name_plural': 'ЗП сервісний відділ'},
        ),
        migrations.RenameField(
            model_name='executorpayment',
            old_name='prmium_1',
            new_name='premium_1',
        ),
        migrations.RenameField(
            model_name='executorpayment',
            old_name='prmium_2',
            new_name='premium_2',
        ),
        migrations.RenameField(
            model_name='executorpayment',
            old_name='prmium_3',
            new_name='premium_3',
        ),
        migrations.AddField(
            model_name='executorpayment',
            name='period',
            field=models.DateField(blank=True, help_text='місяць нарахування ЗП сервісному відділу', null=True, verbose_name='місяць/рік ЗП'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 23), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
