# Generated by Django 2.2.20 on 2021-04-24 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0025_auto_20210423_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 24), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
