# Generated by Django 2.2.20 on 2021-04-27 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0026_auto_20210424_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorPaymentProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'зведені дані ЗП по монтажникам окремон',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workorders.executorpayment',),
        ),
        migrations.AddField(
            model_name='executorpayment',
            name='trip_day_costs_1',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name=' грн добові 1'),
        ),
        migrations.AddField(
            model_name='executorpayment',
            name='trip_day_costs_2',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name=' грн добові 2'),
        ),
        migrations.AddField(
            model_name='executorpayment',
            name='trip_day_costs_3',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name=' грн добові 3'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='qua_work_orders_sum',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть ЗН заг'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='qua_works_sum',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='кількість виконаних робіт співробітником заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='к-ть вик. робіт заг'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='total_payment_2',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='загальна сума ЗП 2'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='total_payment_3',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='загальна сума ЗП 3'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='trip_day_1',
            field=models.FloatField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові 1'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='trip_day_2',
            field=models.FloatField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові 2'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='trip_day_3',
            field=models.FloatField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові 3'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='trip_day_sum',
            field=models.FloatField(blank=True, default=0, help_text='кількість днів на які нараховано добові\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='добові заг'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='work_days_sum',
            field=models.PositiveIntegerField(blank=True, help_text='кількість робочих днів(окрім вихідних)\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='р.д. заг'),
        ),
        migrations.AlterField(
            model_name='executorpayment',
            name='work_days_weekend_sum',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='кількість робочих днів у вихідних\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='р.д.вих заг.'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 27), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='month_executor_pay',
            field=models.DateField(blank=True, help_text='оберіть будь-яку дату в межах місяця нарахування ЗП монтажнику', null=True, verbose_name='місяць/рік ЗП'),
        ),
    ]
