# Generated by Django 2.2.20 on 2021-04-28 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0027_auto_20210427_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorpaymentproxy',
            options={'verbose_name_plural': 'зведені дані ЗП по монтажникам окремо'},
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 28), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
