# Generated by Django 2.2.20 on 2021-04-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0028_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorpayment',
            name='period',
            field=models.DateField(blank=True, help_text='місяць нарахування ЗП сервісному відділу - оберіть будь-яку дату в межах місяця', null=True, verbose_name='місяць/рік ЗП'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 4, 29), help_text='Введіть дату', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_client',
            field=models.IntegerField(blank=True, default=0, help_text='Вартість додаткових витрат для клієнта', null=True, verbose_name='грн за ДВ \nклієнту'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='add_costs_executor',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сума коомпенсації за додаткові витрати монтажнику', null=True, verbose_name='грн за ДВ \nмонтажнику'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='milege_price_client',
            field=models.IntegerField(blank=True, default=0, help_text='Вартість пробігу для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км клієнту'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='milege_price_executor',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сума компенсації за пробіг монтажнику\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='грн за км монтажнику'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='price_of_completed_works',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума за виконані роботи'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='price_of_used_equipment',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Сума за використане обладнання'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sum_price_client',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='сума рахунку для клієнта\nПоле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='сума рахунку'),
        ),
    ]
