# Generated by Django 2.2.20 on 2021-06-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0030_auto_20210512_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executorpaymentproxy',
            options={'verbose_name_plural': 'зведені дані ЗП по монтажникам'},
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 6, 15), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
