# Generated by Django 2.2.20 on 2021-07-06 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0031_auto_20210615_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceplan',
            name='date_create',
            field=models.DateField(default=datetime.date(2021, 7, 6), help_text='Введіть дату', verbose_name='Дата'),
        ),
    ]
