# Generated by Django 2.2.13 on 2021-01-23 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAndService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву товару або послуги', max_length=100, verbose_name='Назва')),
                ('price_client_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта БЕЗ ПДВ')),
                ('price_client_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта з ПДВ')),
                ('price_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість БЕЗ ПДВ')),
                ('price_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість з ПДВ')),
                ('salary_installer', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість роботи монтажника')),
            ],
            options={
                'verbose_name_plural': 'Комплектуючі та послуги',
            },
        ),
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('Київстар', 'Київстар'), ('Лайфсел', 'Лайфсел'), ('Тревел-сім', 'Тревел-сім')], default='Київстар', help_text='Оберіть оператора', max_length=100, verbose_name='Оператор')),
                ('number', models.CharField(help_text='Введіть номер', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{0,11}$')], verbose_name='Номер SIM')),
                ('account_number', models.CharField(help_text='Введіть номер рахунку', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='Рахунок')),
                ('date_receive', models.DateField(help_text='Оберіть дату', null=True, verbose_name='Дата отримання')),
                ('rate_sim', models.FloatField(blank=True, help_text='Введіть суму', max_length=5, null=True, verbose_name='Тариф оператора грн/міс')),
                ('packet_volume', models.PositiveIntegerField(blank=True, help_text='Введіть кількість', null=True, verbose_name="Об'єм пакетних даних Мб/міс")),
                ('rate_volume', models.FloatField(blank=True, help_text='Введіть суму', max_length=5, null=True, verbose_name='Тариф за 1Мб поза пакетом')),
                ('installer', models.CharField(blank=True, choices=[('1', 'Герус В.'), ('2', 'Деміденко Ю.'), ('3', 'Ігнатенко М.')], help_text='Оберіть монтажника, якому видано сім', max_length=1, verbose_name='Монтажник')),
                ('date_given', models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата видачі монтажнику сім')),
            ],
            options={
                'verbose_name_plural': 'Сім-картки',
            },
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введіть номер', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='Номер')),
                ('rate_client_1', models.CharField(blank=True, default='Власна сім', help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф 1')),
                ('rate_client_2', models.CharField(blank=True, help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф 2')),
                ('rate_price', models.IntegerField(blank=True, default=0, help_text='Поле заповниться автоматично, вводити нічого не потрібно', null=True, verbose_name='Вартість грн/міс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='clients.Client', verbose_name='Власник')),
                ('sim_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_1', to='products.Sim', verbose_name='Сім_1')),
                ('sim_2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_2', to='products.Sim', verbose_name='Сім_2')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='Транспортний засіб')),
            ],
            options={
                'verbose_name_plural': 'Бортові Реєстратори (БР)',
            },
        ),
        migrations.CreateModel(
            name='FuelSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=128, verbose_name='Серія')),
                ('number', models.PositiveIntegerField(help_text='Введіть номер', verbose_name='Номер')),
                ('date_manufacturing', models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата виробництва')),
                ('gps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor', to='products.Gps', verbose_name='БР')),
            ],
            options={
                'verbose_name_plural': 'Датчики Вимірювання Рівня Пального (ДВРП)',
            },
        ),
    ]
