# Generated by Django 2.2.13 on 2021-01-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву товару або послуги', max_length=100, verbose_name='Назва')),
                ('price_client_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта БЕЗ ПДВ')),
                ('price_client_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта з ПДВ')),
                ('price_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість БЕЗ ПДВ')),
                ('price_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість з ПДВ')),
            ],
            options={
                'verbose_name_plural': 'Комплектуючі',
            },
        ),
        migrations.DeleteModel(
            name='EquipmentAndService',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Equipment')),
                ('salary_installer', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість роботи монтажника')),
            ],
            options={
                'verbose_name_plural': 'Послуги',
            },
            bases=('products.equipment',),
        ),
    ]
