# Generated by Django 2.2.4 on 2020-03-11 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200311_1701'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sim',
            options={'verbose_name_plural': 'Сім-картки'},
        ),
        migrations.AddField(
            model_name='sim',
            name='rate_client',
            field=models.FloatField(help_text='Введіть суму', max_length=5, null=True, verbose_name='Тариф грн/міс'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='account_number',
            field=models.CharField(help_text='Введіть номер рахунку', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='Рахунок'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='number',
            field=models.CharField(help_text='Введіть номер', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='packet_volume',
            field=models.PositiveIntegerField(help_text='Введіть кількість', verbose_name="Об'єм пакетних даних Мб/міс"),
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введіть номер', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')], verbose_name='Номер')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='Транспортний засіб')),
            ],
            options={
                'verbose_name_plural': 'Реєстратори',
            },
        ),
        migrations.AddField(
            model_name='sim',
            name='gps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim', to='products.Gps', verbose_name='БР'),
        ),
    ]
