# Generated by Django 2.2.13 on 2021-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsensor',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Висота та інші коментарі'),
        ),
        migrations.AddField(
            model_name='fuelsensor',
            name='type',
            field=models.CharField(blank=True, choices=[('аналоговый', 'аналоговый'), ('частотный', 'частотный'), ('цифровой', 'цифровой')], default='цифровой', help_text='Оберіть тип', max_length=100, null=True, verbose_name='Тип датчика'),
        ),
        migrations.AlterField(
            model_name='fuelsensor',
            name='serial',
            field=models.CharField(blank=True, choices=[('2', '2'), ('4', '4'), ('7', '7'), ('10', '10'), ('15', '15'), ('20', '20')], default='7', help_text='Оберіть серію (висоту)', max_length=100, null=True, verbose_name='Серія'),
        ),
    ]
