# Generated by Django 2.2.13 on 2021-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210303_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsensor',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Висота та інше'),
        ),
    ]
