# Generated by Django 2.2.4 on 2020-03-15 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200311_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='date_given',
            field=models.DateField(blank=True, help_text='Оберіть дату', verbose_name='Дата видачі монтажнику сім'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='installer',
            field=models.CharField(blank=True, choices=[('1', 'Герус В.'), ('2', 'Манін В.'), ('3', 'Ігнатенко М.')], help_text='Оберіть монтажника, якому видано сім', max_length=1, verbose_name='Монтажник'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='number',
            field=models.CharField(help_text='Введіть номер', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{0,11}$')], verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_client',
            field=models.CharField(choices=[('1', 'Україна'), ('2', 'Світ'), ('3', 'Пауза')], default='1', help_text='Оберіть тариф для клієнта', max_length=1, verbose_name='Тариф'),
        ),
    ]
