# Generated by Django 2.2.13 on 2021-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210304_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='rate_client',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф'),
        ),
    ]
