# Generated by Django 2.2.20 on 2021-08-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210304_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='rate_client',
        ),
        migrations.RemoveField(
            model_name='gps',
            name='rate_price',
        ),
    ]
