# Generated by Django 2.2.4 on 2020-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200317_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='rate_client',
            field=models.CharField(choices=[('1', 'Україна'), ('2', 'Світ'), ('3', 'Пауза'), ('4', 'Власна сім')], help_text='Оберіть тариф для клієнта', max_length=1, verbose_name='Тариф'),
        ),
    ]
