# Generated by Django 2.2.20 on 2021-08-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210804_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='vehicle',
        ),
    ]
