# Generated by Django 2.2.20 on 2021-09-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_remove_vehicle_gps'),
        ('products', '0008_remove_gps_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsensor',
            name='gps',
        ),
        migrations.AddField(
            model_name='fuelsensor',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor', to='vehicle.Vehicle', verbose_name='ТЗ'),
        ),
        migrations.AddField(
            model_name='gps',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='ТЗ'),
        ),
    ]
