# Generated by Django 2.2.4 on 2020-03-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_fuelsensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsensor',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor', to='products.Gps', verbose_name='ДВРП'),
        ),
    ]
