# Generated by Django 2.2.20 on 2021-09-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsensor',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor', to='vehicle.Vehicle', verbose_name='ТЗ'),
        ),
    ]
