# Generated by Django 2.2.4 on 2020-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200322_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='rate',
        ),
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.CharField(choices=[('Київстар', 'Київстар'), ('Лайфсел', 'Лайфсел'), ('Тревел-сім', 'Тревел-сім')], default='Київстар', help_text='Оберіть оператора', max_length=1, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_client',
            field=models.CharField(choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], default='Україна', help_text='Оберіть тариф для клієнта', max_length=100, verbose_name='Тариф'),
        ),
    ]
