# Generated by Django 2.2.4 on 2020-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200322_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='rate_price',
            field=models.CharField(default=72, max_length=100, verbose_name='Вартість грн/міс'),
        ),
    ]
