# Generated by Django 2.2.4 on 2020-03-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sim_rate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.CharField(choices=[('Київстар', 'Київстар'), ('Лайфсел', 'Лайфсел'), ('Тревел-сім', 'Тревел-сім')], default='Київстар', help_text='Оберіть оператора', max_length=100, verbose_name='Оператор'),
        ),
    ]
