# Generated by Django 2.2.4 on 2020-03-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200322_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='rate_price',
        ),
    ]
