# Generated by Django 2.2.4 on 2020-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_sim_rate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim',
            name='rate_price',
            field=models.PositiveIntegerField(null=True, verbose_name=72),
        ),
    ]
