# Generated by Django 2.2.4 on 2020-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_sim_rate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='rate_price',
            field=models.CharField(default=72, help_text='Змініть вартість', max_length=100, verbose_name='Вартість грн/міс'),
        ),
    ]
