# Generated by Django 2.2.4 on 2020-03-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200322_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='rate_price',
        ),
    ]
