# Generated by Django 2.2.4 on 2020-04-01 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200322_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelsensor',
            options={'verbose_name_plural': 'Датчики Вимірювання Рівня Пального (ДВРП)'},
        ),
        migrations.AlterModelOptions(
            name='gps',
            options={'verbose_name_plural': 'Бортові Реєстратори (БР)'},
        ),
        migrations.RenameField(
            model_name='sim',
            old_name='rate',
            new_name='rate_sim',
        ),
        migrations.AlterField(
            model_name='sim',
            name='number',
            field=models.CharField(help_text='Введіть номер', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{0,11}$')], verbose_name='Номер БР'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='rate_client',
            field=models.CharField(choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф для клієнта', max_length=100, verbose_name='Тариф'),
        ),
    ]
