# Generated by Django 2.2.4 on 2020-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200406_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='rate_price',
            field=models.CharField(blank=True, help_text='Поле заповниться автоматично, вводити нічого не потрібно', max_length=100, null=True, verbose_name='Вартість грн/міс'),
        ),
    ]
