# Generated by Django 2.2.4 on 2020-04-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200406_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='Транспортний засіб'),
        ),
    ]
