# Generated by Django 2.2.4 on 2020-04-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200422_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='vehicle',
            field=models.OneToOneField(blank=True, default='0000', on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='Транспортний засіб'),
        ),
    ]
