# Generated by Django 2.2.4 on 2020-06-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200622_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsensor',
            name='gps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_sensor', to='products.Gps', verbose_name='БР'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='vehicle.Vehicle', verbose_name='Транспортний засіб'),
        ),
    ]
