# Generated by Django 2.2.4 on 2020-08-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20200622_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='clients.Client', verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='rate_client',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Україна+Світ', 'Україна+Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], default='Україна', help_text='Оберіть тариф для клієнта', max_length=100, verbose_name='Тариф'),
        ),
    ]
