# Generated by Django 2.2.4 on 2020-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20200821_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='rate_client',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Україна+Світ', 'Україна+Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], default='Україна', help_text='Оберіть тариф для клієнта', max_length=100, null=True, verbose_name='Тариф'),
        ),
    ]
