# Generated by Django 2.2.13 on 2020-08-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20200821_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gps',
            name='rate_client',
        ),
        migrations.AddField(
            model_name='gps',
            name='rate_client_1',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], default='Україна', help_text='Оберіть тариф для клієнта', max_length=100, null=True, verbose_name='Тариф 1'),
        ),
        migrations.AddField(
            model_name='gps',
            name='rate_client_2',
            field=models.CharField(blank=True, choices=[('Україна', 'Україна'), ('Світ', 'Світ'), ('Пауза', 'Пауза'), ('Власна сім', 'Власна сім')], help_text='Оберіть тариф для клієнта', max_length=100, null=True, verbose_name='Тариф 2'),
        ),
    ]
