# Generated by Django 2.2.13 on 2020-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200826_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelsensor',
            name='date_manufacturing',
            field=models.DateField(blank=True, help_text='Оберіть дату', null=True, verbose_name='Дата виробництва'),
        ),
    ]
