# Generated by Django 2.2.13 on 2020-08-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20200828_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='gps',
        ),
        migrations.AddField(
            model_name='gps',
            name='sim_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_1', to='products.Sim', verbose_name='Sim_1'),
        ),
        migrations.AddField(
            model_name='gps',
            name='sim_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_2', to='products.Sim', verbose_name='Sim_1'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='rate_client_1',
            field=models.CharField(blank=True, default='Україна', help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф 1'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='rate_client_2',
            field=models.CharField(blank=True, help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф 2'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='installer',
            field=models.CharField(blank=True, choices=[('1', 'Герус В.'), ('2', 'Деміденко Ю.'), ('3', 'Ігнатенко М.')], help_text='Оберіть монтажника, якому видано сім', max_length=1, verbose_name='Монтажник'),
        ),
        migrations.AlterField(
            model_name='sim',
            name='operator',
            field=models.CharField(choices=[('Київстар', 'Київстар'), ('Лайфсел', 'Лайфсел'), ('Тревел-сім', 'Тревел-сім'), ('Тревел-сім_укр', 'Тревел-сім_укр')], default='Київстар', help_text='Оберіть оператора', max_length=100, verbose_name='Оператор'),
        ),
    ]
