# Generated by Django 2.2.13 on 2020-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20200828_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='rate_client_1',
            field=models.CharField(blank=True, default='Власна сім', help_text='Тариф заповниться автоматично нічого не потрібно вводити', max_length=100, null=True, verbose_name='Тариф 1'),
        ),
    ]
