# Generated by Django 2.2.13 on 2020-09-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20200919_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gps',
            name='sim_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_1', to='products.Sim', verbose_name='Сім_1'),
        ),
        migrations.AlterField(
            model_name='gps',
            name='sim_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_2', to='products.Sim', verbose_name='Сім_2'),
        ),
    ]
