# Generated by Django 2.2.13 on 2021-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20200919_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAndService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву товару або послуги', max_length=100, verbose_name='Назва')),
                ('price_client_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта БЕЗ ПДВ')),
                ('price_client_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість для клієнта з ПДВ')),
                ('price_taxfree', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість БЕЗ ПДВ')),
                ('price_tax', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Собівартість з ПДВ')),
                ('salary_installer', models.PositiveIntegerField(blank=True, default=0, help_text='Введіть вартість', null=True, verbose_name='Вартість роботи монтажника')),
            ],
        ),
    ]
