# Generated by Django 2.2.13 on 2021-01-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_equipmentandservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentandservice',
            options={'verbose_name_plural': 'Комплектуючі та послуги'},
        ),
    ]
